name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - hydra-core=1.3.2
  - matplotlib=3.10.6
  # Updated from pandas=2.3.2 - not compatible with Python 3.13
  - pandas>=2.2.3
  - pip=24.3.1
  # Updated from scikit-learn=1.3.2 - not compatible with Python 3.13
  - scikit-learn>=1.6.0
  - jupyterlab=4.4.7
  - pip:
      - mlflow==3.3.2
      - wandb==0.21.3
