name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=24.3.1
  - requests=2.24.0
  - scikit-learn=1.5.0
  - pip:
      - mlflow==2.14.3
      - wandb==0.21.3
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
