name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.3.2
  - pytest=8.3.3
  - scipy=1.16.2
  - pip=24.3.1
  - pip:
      - mlflow==2.14.3
      - wandb==0.21.3
