name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pyyaml
  - hydra-core=1.3.2
  - pandas=2.3.2
  - omegaconf=2.3.0
  - pip=24.3.1
  - pip:
      - mlflow==2.14.3
      - wandb==0.21.3
