name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - hydra-core=1.3.2
  - matplotlib>=3.8.0
  - pandas>=2.2.0
  - pip=24.3.1
  - scikit-learn>=1.5.0
  - pip:
      - mlflow==3.3.2
      - wandb==0.21.3
